# Generated by Django 3.0.7 on 2020-07-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listings_bids_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='img_url',
            field=models.ImageField(default='/static/auctions/no_img.png', upload_to='images/'),
        ),
    ]
