# Generated by Django 3.0.7 on 2020-07-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_listings_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='img_url',
            field=models.ImageField(blank=True, default='/static/auctions/no_img.png', upload_to='images/'),
        ),
    ]
