# Generated by Django 3.0.7 on 2020-07-11 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200711_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listings',
            name='img_url',
        ),
    ]
