# Generated by Django 3.0.7 on 2020-07-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_listings_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='img_url',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
