# Generated by Django 3.0.7 on 2020-07-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200711_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='img_url',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
