# Generated by Django 3.0.7 on 2020-07-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200711_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='category',
            field=models.CharField(choices=[('FA', 'Fashion'), ('TO', 'Toys'), ('EL', 'Electronics'), ('HO', 'Home'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
