# Generated by Django 3.0.7 on 2020-07-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auction_listing_watcher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='watcher',
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watching', to='auctions.Auction_Listing'),
        ),
    ]
