# Generated by Django 3.0.7 on 2020-07-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200712_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='user_bid',
            field=models.IntegerField(null=True),
        ),
    ]
