# Generated by Django 3.0.7 on 2020-07-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auction_listing_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
