# Generated by Django 3.0.7 on 2020-07-12 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20200712_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='category',
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='listing_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Misc', max_length=32),
            preserve_default=False,
        ),
    ]
