# Generated by Django 3.0.7 on 2020-07-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20200712_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='listing_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
